//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_MaterialType
    {
        public LU_MaterialType()
        {
            this.LU_Material = new HashSet<LU_Material>();
        }
    
        public int MaterialTypeID { get; set; }
        public string Material_Type { get; set; }
    
        public virtual ICollection<LU_Material> LU_Material { get; set; }
    }
}
