//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spectrum.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_Material
    {
        public int MaterialID { get; set; }
        public int MaterialTypeID { get; set; }
        public string Material { get; set; }
        public Nullable<decimal> Density { get; set; }
        public Nullable<decimal> Environmental_Impact_Factor { get; set; }
        public Nullable<decimal> Thickness { get; set; }
    
        public virtual LU_MaterialType LU_MaterialType { get; set; }
    }
}
